//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketball_Web1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Venue { get; set; }
        public bool Forfeit { get; set; }
        public string AmountPayed { get; set; }
        public int MemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
